import { useCallback, useEffect, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { useNavigation, useRoute } from "@react-navigation/native";
import { useSelector } from "react-redux";
import { ArrowLeft, Banknote, Landmark, PiggyBank, UsersRound, Wallet } from "lucide-react-native";
import { Avatar, EmptyState, IconButton, LoadingScreen, PageHeader, Screen, Status } from "@/components/ui";
import { useAuth } from "@/context/AuthContext";
import { api } from "@/lib/api";
import { money } from "@/lib/format";
import { colors, font, radius, spacing } from "@/theme";

export function ClubDetailScreen() {
    const navigation = useNavigation(); const route = useRoute(); const { user } = useAuth();
    const version = useSelector(state => state.sync.versions.clubs); const [data, setData] = useState(); const clubId = route.params.clubId;
    const load = useCallback(() => api(`/clubs/${clubId}/overview/`).then(setData), [clubId]);
    useEffect(() => { load(); }, [load, version]);
    if (!data) return <LoadingScreen/>;
    const { club, counts } = data; const manager = user.role === "admin" || (user.current_profile === "leader" && club.leader === user.id);
    const currentLoans = data.loans.filter(loan => ["disbursed", "current", "late"].includes(loan.status));
    const otherLoans = data.loans.filter(loan => !["disbursed", "current", "late"].includes(loan.status));
    const currentBalance = currentLoans.reduce((total, loan) => total + Number(loan.balance || 0), 0);
    return <Screen>
      <PageHeader eyebrow={club.zone} title={club.name} action={<IconButton icon={ArrowLeft} label="Retour" onPress={() => navigation.goBack()}/>}/>
      <View style={styles.hero}><View style={styles.heroTop}><View style={styles.mark}><Landmark size={22} color={colors.white}/></View><Status value={club.status}/></View><Text style={styles.description}>{club.description || "Aucune description."}</Text><View style={styles.leader}><Avatar user={{ name: club.leader_name, avatar: club.leader_avatar, selfie: club.leader_selfie }} size={30}/><Text style={styles.leaderText}>Chef: {club.leader_name}</Text></View></View>
      <View style={styles.stats}><Stat icon={UsersRound} value={counts.members} label="Membres"/><Stat icon={Wallet} value={counts.lenders} label="Preteurs"/><Stat icon={PiggyBank} value={counts.active_loans} label="Prets actifs"/></View>
      <View><Text style={styles.sectionTitle}>Emprunts en cours</Text><View style={styles.currentSummary}><View><Text style={styles.currentLabel}>{currentLoans.length} dossier{currentLoans.length > 1 ? "s" : ""} actif{currentLoans.length > 1 ? "s" : ""}</Text><Text style={styles.currentValue}>{money(currentBalance, club.currency)}</Text><Text style={styles.currentHint}>Encours total restant a rembourser</Text></View><View style={styles.currentIcon}><Banknote size={21} color={colors.white}/></View></View>{currentLoans.length ? <View style={styles.list}>{currentLoans.map(loan => <LoanRow key={loan.id} loan={loan} onPress={() => navigation.navigate("LoanDetail", { loanId: loan.id })}/>)}</View> : <EmptyState icon={PiggyBank} title="Aucun emprunt en cours" message="Les prets decaisses apparaitront ici avec leur solde restant."/>}</View>
      <View style={styles.finance}><Text style={styles.sectionTitle}>Situation financiere</Text>
        <Row label="Capital emprunte" value={money(club.finances?.borrowed || 0, club.currency)}/>
        <Row label="Encours de credit" value={money(club.finances?.engaged || 0, club.currency)}/>
        <Row label="Total rembourse" value={money(club.finances?.repaid || 0, club.currency)}/>
        {club.leader_commission_rate !== null && club.leader_commission_rate !== undefined ? <Row label="Commission chef de club" value={`${club.leader_commission_rate} %`}/> : null}
        {club.finances?.leader_commission_collected !== undefined ? <Row label="Commission chef encaissee" value={money(club.finances.leader_commission_collected, club.currency)}/> : null}
        {/* La commission de l'application et l'interet du preteur ne sont visibles que par l'admin. */}
        {club.platform_fee_rate !== null && club.platform_fee_rate !== undefined ? <Row label="Commission application" value={`${club.platform_fee_rate} %`}/> : null}
        {club.interest_rate !== null && club.interest_rate !== undefined ? <Row label="Interet preteur" value={`${club.interest_rate} %`}/> : null}
        {club.borrower_charge_rate ? <Row label="Taux vu par l'emprunteur" value={`${club.borrower_charge_rate} %`}/> : null}
      </View>
      {data.memberships.length ? <View><Text style={styles.sectionTitle}>Comptes et profils</Text><View style={styles.list}>{data.memberships.map(item => <View key={item.id} style={styles.member}><Avatar user={item.user_detail} size={36}/><View style={styles.memberCopy}><Text style={styles.memberName}>{item.user_detail.name}</Text><Text style={styles.memberRole}>{item.role} - {item.user_detail.phone}</Text></View><Status value={item.status}/></View>)}</View></View> : null}
      {otherLoans.length ? <View><Text style={styles.sectionTitle}>Autres dossiers de pret</Text><View style={styles.list}>{otherLoans.map(loan => <LoanRow key={loan.id} loan={loan} onPress={() => navigation.navigate("LoanDetail", { loanId: loan.id })}/>)}</View></View> : null}
    </Screen>;
}
function Stat({ icon: Icon, value, label }) { return <View style={styles.stat}><Icon size={18} color={colors.mintDark}/><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
function Row({ label, value }) { return <View style={styles.row}><Text style={styles.rowLabel}>{label}</Text><Text style={styles.rowValue}>{value}</Text></View>; }
function LoanRow({ loan, onPress }) { return <Pressable onPress={onPress} style={styles.loan}><Avatar user={{ name: loan.borrower_name, avatar: loan.borrower_avatar, selfie: loan.borrower_selfie }} size={38}/><View style={styles.memberCopy}><Text style={styles.memberName}>{loan.purpose}</Text><Text style={styles.memberRole}>{loan.borrower_name} - reste {money(loan.balance, loan.currency)}</Text></View><Status value={loan.status}/></Pressable>; }
const styles = StyleSheet.create({ hero: { gap: spacing.md, padding: spacing.lg, borderRadius: radius.md, backgroundColor: colors.forest }, heroTop: { flexDirection: "row", justifyContent: "space-between" }, mark: { width: 42, height: 42, borderRadius: radius.md, alignItems: "center", justifyContent: "center", backgroundColor: colors.coral }, description: { fontFamily: font.medium, color: colors.white, fontSize: 12, lineHeight: 19 }, leader: { flexDirection: "row", alignItems: "center", gap: spacing.sm }, leaderText: { fontFamily: font.semibold, color: colors.mint, fontSize: 10 }, stats: { flexDirection: "row", gap: spacing.sm }, stat: { flex: 1, minHeight: 94, justifyContent: "space-between", padding: spacing.md, borderRadius: radius.md, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.white }, statValue: { fontFamily: font.bold, color: colors.ink, fontSize: 19 }, statLabel: { fontFamily: font.medium, color: colors.muted, fontSize: 8 }, sectionTitle: { fontFamily: font.bold, color: colors.ink, fontSize: 17, marginBottom: spacing.md }, currentSummary: { minHeight: 122, marginBottom: spacing.sm, padding: spacing.lg, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderRadius: radius.md, backgroundColor: colors.forest }, currentLabel: { fontFamily: font.semibold, color: colors.mint, fontSize: 10 }, currentValue: { marginTop: 5, fontFamily: font.bold, color: colors.white, fontSize: 25 }, currentHint: { marginTop: 4, fontFamily: font.medium, color: colors.mint, fontSize: 8 }, currentIcon: { width: 44, height: 44, borderRadius: radius.md, alignItems: "center", justifyContent: "center", backgroundColor: colors.coral }, finance: { padding: spacing.md, borderRadius: radius.md, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.white }, row: { minHeight: 40, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.line }, rowLabel: { fontFamily: font.medium, color: colors.muted, fontSize: 10 }, rowValue: { fontFamily: font.bold, color: colors.ink, fontSize: 11 }, list: { borderRadius: radius.md, borderWidth: 1, borderColor: colors.line, overflow: "hidden", backgroundColor: colors.white }, member: { minHeight: 64, flexDirection: "row", alignItems: "center", gap: spacing.sm, padding: spacing.md, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.line }, memberIcon: { width: 34, height: 34, borderRadius: 17, alignItems: "center", justifyContent: "center", backgroundColor: colors.mint }, memberCopy: { flex: 1 }, memberName: { fontFamily: font.bold, color: colors.ink, fontSize: 11 }, memberRole: { fontFamily: font.medium, color: colors.muted, fontSize: 8, marginTop: 3 }, loan: { minHeight: 68, flexDirection: "row", alignItems: "center", gap: spacing.sm, padding: spacing.md, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.line } });
