import { useCallback, useEffect, useState } from "react";
import { Alert, Pressable, StyleSheet, Text, View } from "react-native";
import { useNavigation } from "@react-navigation/native";
import { BadgeCheck, Bell, BanknoteArrowDown, ChevronRight, CirclePlus, HandCoins, Landmark, Megaphone, MessageCircle, PiggyBank, Scale, ShieldAlert, TrendingUp, UsersRound, WalletCards } from "lucide-react-native";
import { Avatar, Button, EmptyState, IconButton, LoadingScreen, PageHeader, Reveal, Screen, Status } from "@/components/ui";
import { api, apiCached } from "@/lib/api";
import { greeting, money, shortDateTime } from "@/lib/format";
import { colors, font, radius, shadow, spacing } from "@/theme";
import { useDispatch, useSelector } from "react-redux";
import { invalidate } from "@/store";

const roleCopy = { admin: "Vue de la plateforme", leader: "Pilotage de votre club", lender: "Votre capital en mouvement", borrower: "Vos engagements aujourd'hui", mediator: "Dossiers sous mandat", collector: "Vos encaissements du jour" };
export function DashboardScreen() {
    const navigation = useNavigation(); const dispatch = useDispatch();
    const [data, setData] = useState(); const [counts, setCounts] = useState({ validations: {} }); const [offline, setOffline] = useState(false);
    const version = useSelector(state => state.sync.versions.dashboard);
    const load = useCallback(async () => { const result = await apiCached("/dashboard/", "dashboard"); setData(result.data); setOffline(result.offline); try { setCounts(await api("/activity-counts/")); } catch {} }, []);
    useEffect(() => { load(); }, [load, version]);
    useEffect(() => navigation.addListener("focus", load), [navigation, load]);
    if (!data) return <LoadingScreen/>;
    async function answerInvitation(item, accept) {
        try { await api(`/memberships/${item.id}/accept/`, { method: "POST", body: JSON.stringify({ accept }) }); dispatch(invalidate(["dashboard", "notifications", "clubs", "members", "validations"])); await load(); Alert.alert(accept ? "Demande confirmee" : "Demande refusee", accept ? "Le chef doit aussi confirmer. L'administrateur interviendra seulement apres les deux accords." : "La demande a ete fermee."); }
        catch (error) { Alert.alert("Action impossible", error.message); }
    }
    const currency = data.recent_loans[0]?.currency || "CDF"; const admin = data.user.role === "admin"; const lender = data.user.current_profile === "lender" && !admin; const overview = data.admin_overview;
    return <Screen offline={offline}>
      <PageHeader eyebrow={roleCopy[data.user.current_profile]} title={`${greeting()}, ${data.user.name.split(" ")[0]}`} action={<View style={styles.headerActions}><Avatar user={data.user} size={42}/><IconButton label="Notifications" icon={Bell} badge={data.unread_notifications} onPress={() => navigation.navigate("Notifications")}/></View>}/>
      <Reveal>{admin || lender ? <Pressable onPress={() => navigation.navigate("Balance")} style={styles.balance}><View style={styles.balanceTop}><View style={styles.balanceMain}><Text style={styles.balanceLabel}>Fonds disponibles</Text><Text style={styles.balanceValue}>{money(admin ? overview?.free_after_commitments : data.stats.available_capital, currency)}</Text></View><View style={styles.balanceOpen}><Scale size={18} color={colors.white}/><Text style={styles.balanceOpenText}>Balance nette</Text></View></View><View style={styles.balanceBottom}><BalanceFoot label="Total des mises" value={money(admin ? overview?.total_deposited : data.stats.deposits, currency)}/><View style={styles.balanceDivider}/><BalanceFoot label="Total recupere" value={money(admin ? overview?.total_withdrawn : data.stats.withdrawals, currency)} alignRight/></View></Pressable> : <View style={styles.balance}><View style={styles.balanceMain}><Text style={styles.balanceLabel}>Aide communautaire suivie</Text><Text style={styles.balanceValue}>{money(data.stats.loaned, currency)}</Text></View><View style={styles.balanceMeta}><Text style={styles.balanceMetaLabel}>Rembourse</Text><Text style={styles.balanceMetaValue}>{money(data.stats.repaid, currency)}</Text></View></View>}</Reveal>
      {admin && overview ? <>
        <View><Text style={styles.sectionTitle}>Situation de la plateforme</Text><View style={styles.adminGrid}>
          <AdminMetric label="Fonds disponibles" value={money(overview.free_after_commitments, currency)} tone="mint"/>
          <AdminMetric label="Total des mises" value={money(overview.total_deposited, currency)} tone="sky"/>
          <AdminMetric label="Total recupere" value={money(overview.total_withdrawn, currency)} tone="yellow"/>
          <AdminMetric label={`Placements en cours (${overview.ongoing_placements_count})`} value={money(overview.ongoing_placements, currency)} tone="sky"/>
          <AdminMetric label="Total place" value={money(overview.total_placed, currency)} tone="mint"/>
          <AdminMetric label="Placements a valider" value={money(overview.pending_placements, currency)} tone="coral"/>
        </View></View>
        <View><Text style={styles.sectionTitle}>Revenus encaisses</Text><View style={styles.adminGrid}>
          <AdminMetric label="Commission application" value={money(overview.platform_commission_collected, currency)} tone="coral"/>
          <AdminMetric label="Interet des preteurs" value={money(overview.lender_interest_collected, currency)} tone="mint"/>
          <AdminMetric label="Commission chefs de club" value={money(overview.leader_commission_collected, currency)} tone="yellow"/>
          <AdminMetric label="Total encaisse" value={money(overview.financial_income_collected, currency)} tone="sky"/>
        </View></View>
        <VolumeChart rows={overview.monthly} currency={currency}/>
      </> : null}
      {lender ? <View><Text style={styles.sectionTitle}>Situation de mes placements</Text><View style={styles.adminGrid}><AdminMetric label="Capital disponible" value={money(data.stats.available_capital, currency)} tone="mint"/><AdminMetric label={`Placements en cours (${data.stats.ongoing_placements_count})`} value={money(data.stats.ongoing_placements, currency)} tone="sky"/><AdminMetric label={`Placements recuperes (${data.stats.completed_placements_count})`} value={money(data.stats.completed_placements, currency)} tone="yellow"/><AdminMetric label="Gains encaisses" value={money(data.stats.interest_earned, currency)} tone="coral"/></View></View> : null}
      {admin || lender ? <GainChart rows={data.gain_history || []} currency={currency} admin={admin}/> : null}
      {admin && overview ? <Reveal delay={60}><View style={styles.stats}><Stat icon={Landmark} value={overview.total_clubs} label="Clubs"/><Stat icon={UsersRound} value={overview.borrower_members} label="Emprunteurs"/><Stat icon={HandCoins} value={overview.lender_members} label="Preteurs"/><Stat icon={WalletCards} value={overview.active_loans} label="Prets actifs"/></View></Reveal>
        : <Reveal delay={60}><View style={styles.stats}><Stat icon={Landmark} value={data.stats.clubs} label="Clubs"/><Stat icon={UsersRound} value={data.stats.members} label="Membres"/><Stat icon={WalletCards} value={data.stats.active_loans} label="Prets actifs"/></View></Reveal>}
      <View><Text style={styles.sectionTitle}>Actions rapides</Text><View style={styles.quickActions}>{getActions(admin ? "admin" : data.user.current_profile, counts).map(action => <QuickAction key={action.label} {...action} onPress={() => navigation.navigate(action.screen, action.params)}/>)}</View></View>
      <View style={styles.sectionHeader}><Text style={styles.sectionTitle}>Activite recente</Text><Text style={styles.sectionLink} onPress={() => navigation.navigate("Loans")}>Tout voir</Text></View>
      {data.membership_invitations?.length ? <View style={styles.invitationList}>{data.membership_invitations.map(item => <View key={item.id} style={styles.invitation}><View style={styles.invitationTop}><View style={styles.invitationIcon}><UsersRound size={19} color={colors.forest}/></View><View style={styles.invitationCopy}><Text style={styles.invitationTitle}>Adhesion a {item.club_name}</Text><Text style={styles.invitationText}>Profil demande: {item.role === "lender" ? "Preteur" : "Emprunteur"}</Text><Text style={styles.invitationDate}>Creee le {shortDateTime(item.created_at)}</Text></View><Status value="pending"/></View><Text style={styles.invitationNote}>Vous et le chef pouvez confirmer dans n'importe quel ordre. L'admin validera ensuite.</Text><View style={styles.invitationActions}><View style={styles.invitationButton}><Button label="Refuser" variant="ghost" onPress={() => answerInvitation(item, false)}/></View><View style={styles.invitationButton}><Button label="Confirmer" onPress={() => answerInvitation(item, true)}/></View></View></View>)}</View> : null}
      {data.recent_loans.length ? <View style={styles.loanList}>{data.recent_loans.map(loan => <Pressable key={loan.id} onPress={() => navigation.navigate("LoanDetail", { loanId: loan.id })} style={({ pressed }) => [styles.loanRow, pressed && styles.rowPressed]}><Avatar user={{ name: loan.borrower_name, avatar: loan.borrower_avatar, selfie: loan.borrower_selfie }} size={40}/><View style={styles.loanText}><Text style={styles.loanPurpose} numberOfLines={1}>{loan.purpose}</Text><Text style={styles.loanClub}>{lender && loan.my_funding ? `Place ${money(loan.my_funding.amount, loan.currency)}` : loan.club_name}</Text><Text style={styles.loanDate}>Cree le {shortDateTime(loan.created_at)}</Text></View><View style={styles.loanEnd}><Text style={styles.loanAmount}>{money(lender && loan.my_funding ? loan.my_funding.remaining_return : loan.balance, loan.currency)}</Text><Status value={loan.status}/></View><ChevronRight size={17} color={colors.muted}/></Pressable>)}</View> : <EmptyState icon={PiggyBank} title="Aucun pret" message="Les demandes et financements recents apparaitront ici."/>}
    </Screen>;
}
function Stat({ icon: Icon, value, label }) { return <View style={styles.stat}><Icon size={18} color={colors.mintDark}/><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
function BalanceFoot({ label, value, alignRight }) { return <View style={[styles.balanceFoot, alignRight && styles.alignRight]}><Text style={styles.balanceFootLabel}>{label}</Text><Text style={styles.balanceFootValue} numberOfLines={1} adjustsFontSizeToFit>{value}</Text></View>; }
function getActions(role, counts) {
    if (role === "admin") return [
        { label: "Mise", icon: CirclePlus, color: colors.mint, screen: "AdminOperations", params: { mode: "deposit" } },
        { label: "Recuperation", icon: BanknoteArrowDown, color: colors.sky, screen: "AdminOperations", params: { mode: "withdrawal" } },
        { label: "Emprunt", icon: WalletCards, color: colors.yellow, screen: "AdminOperations", params: { mode: "loan" } },
        { label: "Placement", icon: TrendingUp, color: colors.coralSoft, screen: "AdminOperations", params: { mode: "funding" } },
        { label: "Encaisser", icon: HandCoins, color: colors.mint, screen: "Collections", count: counts.collections },
        { label: "Validation", icon: BadgeCheck, color: colors.sky, screen: "Validations", count: counts.validations?.total },
        { label: "Validation users", icon: UsersRound, color: colors.mint, screen: "AccountValidations", count: counts.validations?.loans },
        { label: "Annonce", icon: Megaphone, color: colors.yellow, screen: "OperationForm", params: { mode: "announcement" } },
    ];
    if (role === "collector") return [{ label: "Encaisser", icon: HandCoins, color: colors.mint, screen: "Collections", count: counts.collections }];
    if (role === "leader") return [{ label: "Validations", icon: BadgeCheck, color: colors.mint, screen: "Validations", count: counts.validations?.total }, { label: "Gestion", icon: UsersRound, color: colors.yellow, screen: "Gestion", count: counts.management_total }, { label: "Annonce", icon: Megaphone, color: colors.coralSoft, screen: "OperationForm", params: { mode: "announcement" } }];
    if (role === "lender") return [{ label: "Balance", icon: Scale, color: colors.mint, screen: "Balance" }, { label: "Mise", icon: CirclePlus, color: colors.sky, screen: "OperationForm", params: { mode: "deposit" } }, { label: "Recuperation", icon: WalletCards, color: colors.yellow, screen: "OperationForm", params: { mode: "withdrawal" } }, { label: "Reclamation", icon: ShieldAlert, color: colors.coralSoft, screen: "OperationForm", params: { mode: "dispute" }, count: counts.disputes }];
    return [{ label: "Nouveau pret", icon: CirclePlus, color: colors.mint, screen: "LoanRequest" }, { label: "Mes prets", icon: WalletCards, color: colors.yellow, screen: "Loans", count: counts.collective_requests }, { label: "Chat du club", icon: MessageCircle, color: colors.sky, screen: "Chat", count: counts.chat }, { label: "Reclamation", icon: ShieldAlert, color: colors.coralSoft, screen: "OperationForm", params: { mode: "dispute" }, count: counts.disputes }];
}
function QuickAction({ label, icon: Icon, color, onPress, count }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.quickAction, pressed && styles.quickPressed]}><View style={[styles.quickIcon, { backgroundColor: color }]}><Icon size={20} color={colors.forest}/>{count > 0 ? <View style={styles.quickBadge}><Text style={styles.quickBadgeText}>{count > 99 ? "99+" : count}</Text></View> : null}</View><Text style={styles.quickLabel}>{label}</Text></Pressable>; }
function AdminMetric({ label, value, tone }) { return <View style={[styles.adminMetric, styles[`adminMetric_${tone}`]]}><Text style={styles.adminMetricLabel}>{label}</Text><Text style={styles.adminMetricValue} numberOfLines={1} adjustsFontSizeToFit>{value}</Text></View>; }
function VolumeChart({ rows, currency }) { const maximum = Math.max(1, ...rows.flatMap(row => [Number(row.deposits), Number(row.loans)])); return <View style={styles.chart}><View style={styles.chartHeader}><View><Text style={styles.sectionTitle}>Evolution sur 6 mois</Text><Text style={styles.chartSubtitle}>Mises et aides empruntees</Text></View><View style={styles.legend}><Legend color={colors.mintDark} label="Mises"/><Legend color={colors.coral} label="Emprunts"/></View></View><View style={styles.chartBars}>{rows.map(row => <View key={row.key} style={styles.chartGroup}><View style={styles.bars}><View style={[styles.bar, styles.depositBar, { height: Math.max(4, Number(row.deposits) / maximum * 112) }]}/><View style={[styles.bar, styles.loanBar, { height: Math.max(4, Number(row.loans) / maximum * 112) }]}/></View><Text style={styles.chartLabel}>{row.label}</Text></View>)}</View><Text style={styles.chartTotal}>Pic de periode: {money(maximum, currency)}</Text></View>; }
function GainChart({ rows, currency, admin }) { const maximum = Math.max(1, ...rows.map(row => Number(row.amount))); const total = rows.reduce((sum, row) => sum + Number(row.amount), 0); return <View style={styles.gainChart}><View style={styles.chartHeader}><View><Text style={[styles.sectionTitle, styles.gainTitle]}>Evolution des gains</Text><Text style={[styles.chartSubtitle, styles.gainSubtitle]}>{admin ? "Interets, commissions et frais encaisses" : "Ma part d'interets reellement recue"}</Text></View><View style={styles.gainTotal}><Text style={styles.gainTotalLabel}>6 mois</Text><Text style={styles.gainTotalValue}>{money(total, currency)}</Text></View></View><View style={styles.gainBars}>{rows.map(row => <View key={row.key} style={styles.gainGroup}><View style={styles.gainTrack}><View style={[styles.gainBar, { height: Math.max(5, Number(row.amount) / maximum * 94) }]}/></View><Text style={[styles.chartLabel, styles.gainLabel]}>{row.label}</Text></View>)}</View></View>; }
function Legend({ color, label }) { return <View style={styles.legendItem}><View style={[styles.legendDot, { backgroundColor: color }]}/><Text style={styles.legendText}>{label}</Text></View>; }
const styles = StyleSheet.create({
    headerActions: { flexDirection: "row", alignItems: "center", gap: spacing.sm },
    balance: { minHeight: 190, borderRadius: radius.md, backgroundColor: colors.forest, padding: spacing.lg, justifyContent: "space-between", gap: spacing.lg, ...shadow }, balanceTop: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: spacing.md }, balanceMain: { flex: 1 }, balanceLabel: { fontFamily: font.medium, color: colors.mint, fontSize: 12 }, balanceValue: { fontFamily: font.bold, color: colors.white, fontSize: 30, marginTop: spacing.xs }, balanceOpen: { alignItems: "flex-end", gap: 5 }, balanceOpenText: { fontFamily: font.semibold, color: colors.mint, fontSize: 8 }, balanceBottom: { paddingTop: spacing.md, flexDirection: "row", alignItems: "center", borderTopWidth: 1, borderTopColor: "#35675C" }, balanceFoot: { flex: 1 }, alignRight: { alignItems: "flex-end" }, balanceFootLabel: { fontFamily: font.medium, color: colors.mint, fontSize: 9 }, balanceFootValue: { marginTop: 4, maxWidth: 145, fontFamily: font.bold, color: colors.white, fontSize: 13 }, balanceDivider: { width: 1, height: 34, marginHorizontal: spacing.md, backgroundColor: "#35675C" }, balanceMeta: { alignSelf: "flex-end", alignItems: "flex-end" }, balanceMetaLabel: { fontFamily: font.medium, color: colors.mint, fontSize: 10 }, balanceMetaValue: { fontFamily: font.bold, color: colors.yellow, fontSize: 13, marginTop: 4 },
    stats: { flexDirection: "row", gap: spacing.sm }, stat: { flex: 1, minHeight: 104, borderRadius: radius.md, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line, padding: spacing.md, justifyContent: "space-between", ...shadow }, statValue: { fontFamily: font.bold, fontSize: 21, color: colors.ink }, statLabel: { fontFamily: font.medium, fontSize: 10, color: colors.muted }, sectionHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, sectionTitle: { fontFamily: font.bold, fontSize: 18, color: colors.ink }, sectionLink: { fontFamily: font.semibold, fontSize: 12, color: colors.coral },
    adminGrid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, marginTop: spacing.md }, adminMetric: { width: "48%", minHeight: 92, justifyContent: "space-between", padding: spacing.md, borderRadius: radius.md }, adminMetric_mint: { backgroundColor: colors.mint }, adminMetric_sky: { backgroundColor: colors.sky }, adminMetric_yellow: { backgroundColor: "#FFF0C5" }, adminMetric_coral: { backgroundColor: colors.coralSoft }, adminMetricLabel: { fontFamily: font.semibold, color: colors.muted, fontSize: 9 }, adminMetricValue: { fontFamily: font.bold, color: colors.ink, fontSize: 16 },
    chart: { gap: spacing.md, padding: spacing.md, borderRadius: radius.md, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.white }, chartHeader: { flexDirection: "row", justifyContent: "space-between", gap: spacing.sm }, chartSubtitle: { fontFamily: font.medium, color: colors.muted, fontSize: 9, marginTop: 3 }, legend: { gap: 4 }, legendItem: { flexDirection: "row", alignItems: "center", gap: 5 }, legendDot: { width: 7, height: 7, borderRadius: 4 }, legendText: { fontFamily: font.medium, color: colors.muted, fontSize: 8 }, chartBars: { height: 142, flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: colors.line }, chartGroup: { flex: 1, height: 136, alignItems: "center", justifyContent: "flex-end" }, bars: { height: 116, flexDirection: "row", alignItems: "flex-end", gap: 3 }, bar: { width: 8, borderTopLeftRadius: 3, borderTopRightRadius: 3 }, depositBar: { backgroundColor: colors.mintDark }, loanBar: { backgroundColor: colors.coral }, chartLabel: { fontFamily: font.medium, color: colors.muted, fontSize: 7, marginTop: 5 }, chartTotal: { fontFamily: font.semibold, color: colors.forest, fontSize: 9 },
    gainChart: { gap: spacing.md, padding: spacing.md, borderRadius: radius.md, backgroundColor: colors.forest }, gainTitle: { color: colors.white }, gainSubtitle: { color: colors.mint }, gainLabel: { color: colors.mint }, gainTotal: { alignItems: "flex-end" }, gainTotalLabel: { fontFamily: font.medium, color: colors.mint, fontSize: 8 }, gainTotalValue: { marginTop: 3, fontFamily: font.bold, color: colors.yellow, fontSize: 12 }, gainBars: { height: 120, flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: "#35675C" }, gainGroup: { flex: 1, alignItems: "center" }, gainTrack: { height: 98, justifyContent: "flex-end" }, gainBar: { width: 14, borderTopLeftRadius: 4, borderTopRightRadius: 4, backgroundColor: colors.coral },
    quickActions: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, marginTop: spacing.md }, quickAction: { width: "31.8%", minHeight: 84, gap: spacing.sm, padding: spacing.sm, borderRadius: radius.md, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line }, quickPressed: { opacity: 0.75, transform: [{ scale: 0.98 }] }, quickIcon: { width: 36, height: 36, borderRadius: radius.md, alignItems: "center", justifyContent: "center" }, quickBadge: { position: "absolute", top: -7, right: -9, minWidth: 20, height: 20, paddingHorizontal: 4, borderRadius: 10, alignItems: "center", justifyContent: "center", backgroundColor: colors.coral, borderWidth: 2, borderColor: colors.white }, quickBadgeText: { fontFamily: font.bold, color: colors.white, fontSize: 8 }, quickLabel: { fontFamily: font.bold, color: colors.ink, fontSize: 9 },
    invitationList: { gap: spacing.md }, invitation: { gap: spacing.md, padding: spacing.md, borderRadius: radius.md, borderWidth: 1, borderColor: colors.coral, backgroundColor: colors.white }, invitationTop: { flexDirection: "row", alignItems: "center", gap: spacing.sm }, invitationIcon: { width: 40, height: 40, alignItems: "center", justifyContent: "center", borderRadius: radius.md, backgroundColor: colors.mint }, invitationCopy: { flex: 1 }, invitationTitle: { fontFamily: font.bold, color: colors.ink, fontSize: 13 }, invitationText: { fontFamily: font.medium, color: colors.muted, fontSize: 9, marginTop: 3 }, invitationDate: { fontFamily: font.medium, color: colors.mintDark, fontSize: 8, marginTop: 4 }, invitationNote: { fontFamily: font.medium, color: colors.muted, fontSize: 10, lineHeight: 16 }, invitationActions: { flexDirection: "row", gap: spacing.sm }, invitationButton: { flex: 1 }, loanList: { borderRadius: radius.md, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.white }, loanRow: { minHeight: 84, padding: spacing.md, flexDirection: "row", alignItems: "center", gap: spacing.sm, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.line }, loanIcon: { width: 38, height: 38, borderRadius: radius.md, backgroundColor: colors.mint, alignItems: "center", justifyContent: "center" }, loanText: { flex: 1 }, loanPurpose: { fontFamily: font.semibold, color: colors.ink, fontSize: 13 }, loanClub: { fontFamily: font.regular, color: colors.muted, fontSize: 10, marginTop: 3 }, loanDate: { fontFamily: font.medium, color: colors.mintDark, fontSize: 8, marginTop: 4 }, loanEnd: { alignItems: "flex-end", gap: 4 }, loanAmount: { fontFamily: font.bold, fontSize: 12, color: colors.ink }, rowPressed: { backgroundColor: colors.paper },
});
