# Generated by Django 5.2.16 on 2026-08-09 14:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('leader', 'Chef de club'), ('lender', 'Preteur'), ('borrower', 'Emprunteur'), ('mediator', 'Mediateur')], default='borrower', max_length=16)),
                ('kyc_verified', models.BooleanField(default=False)),
                ('accepted_terms_at', models.DateTimeField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('zone', models.CharField(max_length=120)),
                ('currency', models.CharField(default='CDF', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('suspended', 'Suspendu'), ('frozen', 'Gele'), ('archived', 'Archive')], default='draft', max_length=16)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('penalty_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('platform_fee_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('min_loan', models.DecimalField(decimal_places=2, default=Decimal('10000'), max_digits=16)),
                ('max_loan', models.DecimalField(decimal_places=2, default=Decimal('1000000'), max_digits=16)),
                ('min_duration_months', models.PositiveSmallIntegerField(default=1)),
                ('max_duration_months', models.PositiveSmallIntegerField(default=12)),
                ('withdrawal_notice_days', models.PositiveSmallIntegerField(default=7)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_clubs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=80)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=64)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='core.club')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='CDF', max_length=3)),
                ('reference', models.CharField(editable=False, max_length=32, unique=True)),
                ('payment_method', models.CharField(default='cash', max_length=40)),
                ('provider_reference', models.CharField(blank=True, max_length=100)),
                ('proof', models.ImageField(blank=True, upload_to='deposit-proofs/')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('validated', 'Valide'), ('rejected', 'Refuse'), ('cancelled', 'Annule')], default='pending', max_length=16)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='core.club')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='CDF', max_length=3)),
                ('reference', models.CharField(editable=False, max_length=32, unique=True)),
                ('purpose', models.CharField(max_length=240)),
                ('estimated_income', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('guarantors', models.TextField(blank=True)),
                ('duration_months', models.PositiveSmallIntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fee_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('interest_total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('fee_total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_due', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('review', 'En etude'), ('approved', 'Valide'), ('rejected', 'Refuse'), ('disbursed', 'Decaisse'), ('current', 'En cours'), ('late', 'En retard'), ('repaid', 'Rembourse'), ('disputed', 'Litigieux'), ('cancelled', 'Annule')], default='submitted', max_length=16)),
                ('decision_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_loans', to=settings.AUTH_USER_MODEL)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='core.club')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('kind', models.CharField(default='info', max_length=40)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='CDF', max_length=3)),
                ('reference', models.CharField(editable=False, max_length=32, unique=True)),
                ('payment_method', models.CharField(default='cash', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Valide'), ('rejected', 'Refuse'), ('reversed', 'Contrepasse')], default='validated', max_length=16)),
                ('principal_paid', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('interest_paid', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('fee_paid', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('penalty_paid', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='core.loan')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_repayments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='CDF', max_length=3)),
                ('reference', models.CharField(editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('submitted', 'Soumise'), ('review', 'En etude'), ('approved', 'Validee'), ('rejected', 'Refusee'), ('paid', 'Payee'), ('cancelled', 'Annulee')], default='submitted', max_length=16)),
                ('decision_reason', models.TextField(blank=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='core.club')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField()),
                ('principal_due', models.DecimalField(decimal_places=2, max_digits=16)),
                ('interest_due', models.DecimalField(decimal_places=2, max_digits=16)),
                ('fee_due', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('penalty_due', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('status', models.CharField(choices=[('upcoming', 'A venir'), ('due', 'Due'), ('partial', 'Partielle'), ('paid', 'Payee'), ('late', 'En retard'), ('cancelled', 'Annulee')], default='upcoming', max_length=16)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='core.loan')),
            ],
            options={
                'ordering': ['due_date', 'number'],
                'constraints': [models.UniqueConstraint(fields=('loan', 'number'), name='unique_loan_installment')],
            },
        ),
        migrations.CreateModel(
            name='LoanFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_fundings', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fundings', to='core.loan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('loan', 'lender'), name='unique_loan_lender')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('leader', 'Chef'), ('lender', 'Preteur'), ('borrower', 'Emprunteur'), ('treasurer', 'Tresorier')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('active', 'Actif'), ('blocked', 'Bloque'), ('suspended', 'Suspendu'), ('left', 'Sorti')], default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='core.club')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_memberships', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('club', 'user', 'role'), name='unique_club_user_role')],
            },
        ),
    ]
