# Generated by Django 5.2.16 on 2026-08-09 15:48

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_unique_phones(apps, schema_editor):
    User = apps.get_model("core", "User")
    demo_numbers = {
        "admin": "+243810000001",
        "chef": "+243810000002",
        "preteur": "+243810000003",
        "emprunteur": "+243810000004",
    }
    for index, user in enumerate(User.objects.order_by("id"), start=100):
        user.phone = demo_numbers.get(user.username) or f"+24389999{index:04d}"
        user.save(update_fields=["phone"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=24)),
                ('code_hash', models.CharField(max_length=160)),
                ('purpose', models.CharField(choices=[('register', 'Inscription'), ('login', 'Connexion'), ('recovery', 'Recuperation')], max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='identity_document',
            field=models.FileField(blank=True, upload_to='kyc/documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='selfie',
            field=models.ImageField(blank=True, upload_to='kyc/selfies/'),
        ),
        migrations.RunPython(populate_unique_phones, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.CreateModel(
            name='ClubMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('text', 'Message'), ('announcement', 'Annonce'), ('private', 'Prive')], default='text', max_length=16)),
                ('body', models.TextField(max_length=2000)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='core.club')),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_club_messages', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_club_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_club_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(max_length=32)),
                ('operation_id', models.CharField(blank=True, max_length=64)),
                ('subject', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('review', 'En analyse'), ('resolved', 'Resolu'), ('rejected', 'Rejete'), ('closed', 'Clos')], default='open', max_length=16)),
                ('frozen', models.BooleanField(default=False)),
                ('decision', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_disputes', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='core.club')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
