# Generated by Django 5.2.16 on 2026-08-09 16:31

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_otpchallenge_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_name', models.CharField(default='REBOOT CLUB', max_length=80)),
                ('default_currency', models.CharField(default='CDF', max_length=3)),
                ('default_interest_rate', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5)),
                ('default_penalty_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('default_commission_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('max_loan', models.DecimalField(decimal_places=2, default=Decimal('1000000'), max_digits=16)),
                ('require_double_validation', models.BooleanField(default=True)),
                ('kyc_required', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('support_phone', models.CharField(blank=True, max_length=24)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('phone', models.CharField(max_length=24)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('leader', 'Chef de club'), ('lender', 'Preteur'), ('borrower', 'Emprunteur'), ('mediator', 'Mediateur')], max_length=16)),
                ('membership_role', models.CharField(blank=True, choices=[('leader', 'Chef'), ('lender', 'Preteur'), ('borrower', 'Emprunteur'), ('treasurer', 'Tresorier')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptee'), ('cancelled', 'Annulee'), ('expired', 'Expiree')], default='pending', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.club')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
