# Generated by Django 5.2.16 on 2026-08-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_platformsettings_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='funding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='scheduled_disbursement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='active_profile',
            field=models.CharField(blank=True, choices=[('admin', 'Administrateur'), ('leader', 'Chef de club'), ('lender', 'Preteur'), ('borrower', 'Emprunteur'), ('mediator', 'Mediateur')], max_length=16),
        ),
    ]
