# Generated by Django 5.2.16 on 2026-08-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_loan_funding_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanfunding',
            name='expected_gain',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='loanfunding',
            name='interest_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='loanfunding',
            name='principal_repaid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
