# Generated by Django 5.2.16 on 2026-08-10 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_loanfunding_expected_gain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_membership_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_clubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='club',
            constraint=models.UniqueConstraint(condition=models.Q(('leader__isnull', False)), fields=('leader',), name='one_club_per_leader'),
        ),
    ]
