# Generated by Django 5.2.16 on 2026-08-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_membership_accepted_at_membership_invited_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='membership_role',
            field=models.CharField(blank=True, choices=[('leader', 'Chef'), ('lender', 'Preteur'), ('borrower', 'Emprunteur')], max_length=16),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('leader', 'Chef'), ('lender', 'Preteur'), ('borrower', 'Emprunteur')], max_length=16),
        ),
    ]
