# Generated by Django 5.2.16 on 2026-08-10 18:22

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def preserve_membership_approvals(apps, schema_editor):
    Membership = apps.get_model('core', 'Membership')
    for membership in Membership.objects.select_related('club').all():
        member_at = None
        leader_at = None
        if membership.status == 'active':
            member_at = membership.accepted_at or membership.reviewed_at or membership.created_at
            leader_at = membership.reviewed_at or membership.created_at
        else:
            if membership.accepted_at or membership.invited_by_id is None:
                member_at = membership.accepted_at or membership.created_at
            if membership.invited_by_id == membership.club.leader_id or membership.user_id == membership.club.leader_id:
                leader_at = membership.created_at
        Membership.objects.filter(pk=membership.pk).update(member_approved_at=member_at, leader_approved_at=leader_at)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_invitation_membership_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='leader_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='member_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='admin_borrower_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.CreateModel(
            name='KYCApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=180)),
                ('occupation', models.CharField(max_length=180)),
                ('employer_or_business', models.CharField(blank=True, max_length=180)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('address', models.CharField(max_length=240)),
                ('document_type', models.CharField(choices=[('voter_card', "Carte d'electeur"), ('national_id', 'Carte nationale'), ('passport', 'Passeport')], default='voter_card', max_length=24)),
                ('document_number', models.CharField(max_length=80)),
                ('identity_document', models.FileField(upload_to='kyc/documents/')),
                ('selfie', models.ImageField(upload_to='kyc/selfies/')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('review', 'En verification'), ('approved', 'Valide'), ('rejected', 'Refuse')], default='submitted', max_length=16)),
                ('decision_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_kyc_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(preserve_membership_approvals, migrations.RunPython.noop),
    ]
