# Generated by Django 5.2.16 on 2026-08-18 20:19

import core.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_normalize_legacy_occupations"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="allowed_durations",
            field=models.JSONField(blank=True, default=core.models.default_durations),
        ),
        migrations.AddField(
            model_name="club",
            name="leader_commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5.00"),
                help_text="Commission du chef de club en % du capital emprunte.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="max_collective_borrowers",
            field=models.PositiveSmallIntegerField(
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="installment",
            name="leader_commission_due",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="loan",
            name="collection_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="collected_loans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="collection_agent_assigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="duration_code",
            field=models.CharField(
                choices=[
                    ("1w", "1 semaine"),
                    ("2w", "2 semaines"),
                    ("1m", "1 mois"),
                    ("2m", "2 mois"),
                    ("3m", "3 mois"),
                    ("4m", "4 mois"),
                    ("5m", "5 mois"),
                    ("6m", "6 mois"),
                    ("12m", "1 annee"),
                ],
                default="3m",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="installment_total",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="loan",
            name="is_collective",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="loan",
            name="leader_commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Commission du chef de club en % du capital.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="leader_commission_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="loan",
            name="repayment_frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Chaque jour"),
                    ("weekly", "Chaque semaine"),
                    ("monthly", "Chaque mois"),
                    ("quarterly", "Tous les 3 mois"),
                    ("four_monthly", "Tous les 4 mois"),
                    ("biannual", "Tous les 6 mois"),
                    ("annual", "Chaque annee"),
                ],
                default="monthly",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="loanfunding",
            name="decision_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="loanfunding",
            name="pending_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="loanfunding",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loanfunding",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviewed_fundings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loanfunding",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="default_collective_borrowers",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="default_leader_commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5.00"),
                help_text="Commission du chef de club en % du capital emprunte.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="repayment",
            name="leader_commission_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="user",
            name="anonymous_lender",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="club",
            name="interest_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("20.00"),
                help_text="Interet du preteur en % du capital emprunte.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="platform_fee_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10.00"),
                help_text="Commission de l'application en % du capital emprunte.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deposits",
                to="core.club",
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrateur"),
                    ("leader", "Chef de club"),
                    ("lender", "Preteur"),
                    ("borrower", "Emprunteur"),
                    ("mediator", "Mediateur"),
                    ("collector", "Mandataire d'encaissement"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="duration_months",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="loan",
            name="fee_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Commission de l'application en % du capital.",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="interest_rate",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Interet du preteur en % du capital.",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("pending_partners", "En attente des co-emprunteurs"),
                    ("submitted", "Soumis"),
                    ("review", "En etude"),
                    ("approved", "Valide"),
                    ("rejected", "Refuse"),
                    ("disbursed", "Decaisse"),
                    ("current", "En cours"),
                    ("late", "En retard"),
                    ("repaid", "Rembourse"),
                    ("disputed", "Litigieux"),
                    ("cancelled", "Annule"),
                ],
                default="submitted",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="loanfunding",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="platformsettings",
            name="default_commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10.00"),
                help_text="Commission de l'application en % du capital emprunte.",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="platformsettings",
            name="default_interest_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("20.00"),
                help_text="Interet du preteur en % du capital emprunte.",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="active_profile",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Administrateur"),
                    ("leader", "Chef de club"),
                    ("lender", "Preteur"),
                    ("borrower", "Emprunteur"),
                    ("mediator", "Mediateur"),
                    ("collector", "Mandataire d'encaissement"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrateur"),
                    ("leader", "Chef de club"),
                    ("lender", "Preteur"),
                    ("borrower", "Emprunteur"),
                    ("mediator", "Mediateur"),
                    ("collector", "Mandataire d'encaissement"),
                ],
                default="borrower",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="withdrawal",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="withdrawals",
                to="core.club",
            ),
        ),
        migrations.CreateModel(
            name="LoanPurpose",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160, unique=True)),
                ("description", models.CharField(blank=True, max_length=240)),
                ("is_active", models.BooleanField(default=True)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_loan_purposes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["position", "name"],
            },
        ),
        migrations.AddField(
            model_name="loan",
            name="purpose_reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loans",
                to="core.loanpurpose",
            ),
        ),
        migrations.CreateModel(
            name="LoanBorrower",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "share_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("share_is_manual", models.BooleanField(default=False)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Acceptee"),
                            ("pending", "En attente"),
                            ("declined", "Refusee"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("decision_reason", models.TextField(blank=True)),
                (
                    "principal_repaid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "total_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrowers",
                        to="core.loan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("loan", "user"), name="unique_loan_borrower"
                    )
                ],
            },
        ),
    ]
