# Generated by Django 5.2.16 on 2026-08-29 16:37

import django.db.models.deletion
import uuid
from datetime import date
from decimal import Decimal, ROUND_HALF_UP
from django.conf import settings
from django.db import migrations, models


CENT = Decimal("0.01")


def money(value):
    return Decimal(value).quantize(CENT, rounding=ROUND_HALF_UP)


def split_amount(total, parts):
    if parts <= 0:
        return []
    total = money(total)
    base = money(total / parts)
    return [base] * (parts - 1) + [money(total - base * (parts - 1))]


def proportional_totals(total, shares, loan_amount):
    allocated = Decimal("0")
    values = []
    for index, share in enumerate(shares):
        value = money(total - allocated) if index == len(shares) - 1 else money(Decimal(total) * share.share_amount / loan_amount)
        values.append(value)
        allocated += value
    return values


def backfill_collective_debts(apps, schema_editor):
    Loan = apps.get_model("core", "Loan")
    LoanBorrower = apps.get_model("core", "LoanBorrower")
    BorrowerInstallment = apps.get_model("core", "BorrowerInstallment")
    active_statuses = ["disbursed", "current", "late", "disputed", "repaid"]
    for loan in Loan.objects.filter(is_collective=True, status__in=active_statuses).prefetch_related("installments", "borrowers"):
        installments = list(loan.installments.order_by("due_date", "number"))
        shares = list(loan.borrowers.filter(status="accepted").order_by("created_at"))
        if not installments or not shares or not loan.amount:
            continue
        component_totals = {
            "principal": proportional_totals(loan.amount, shares, loan.amount),
            "interest": proportional_totals(loan.interest_total, shares, loan.amount),
            "fee": proportional_totals(loan.fee_total, shares, loan.amount),
            "leader_commission": proportional_totals(loan.leader_commission_total, shares, loan.amount),
        }
        for position, share in enumerate(shares):
            if loan.collection_agent_id:
                LoanBorrower.objects.filter(pk=share.pk).update(
                    collection_agent_id=loan.collection_agent_id,
                    collection_agent_assigned_at=loan.collection_agent_assigned_at,
                )
            schedules = {key: split_amount(values[position], len(installments)) for key, values in component_totals.items()}
            paid_cursor = Decimal(share.total_paid)
            for index, global_installment in enumerate(installments):
                row = BorrowerInstallment.objects.create(
                    loan_borrower=share, number=global_installment.number, due_date=global_installment.due_date,
                    principal_due=schedules["principal"][index], interest_due=schedules["interest"][index],
                    fee_due=schedules["fee"][index], leader_commission_due=schedules["leader_commission"][index],
                )
                paid_values = {key: Decimal("0") for key in ["principal", "interest", "fee", "leader_commission", "penalty"]}
                for key in ["penalty", "fee", "leader_commission", "interest", "principal"]:
                    due = getattr(row, f"{key}_due")
                    allocation = min(paid_cursor, due)
                    paid_values[key] = allocation
                    paid_cursor -= allocation
                paid_amount = sum(paid_values.values(), Decimal("0"))
                total_due = row.principal_due + row.interest_due + row.fee_due + row.leader_commission_due + row.penalty_due
                status = "paid" if paid_amount >= total_due else "partial" if paid_amount > 0 else "late" if row.due_date < date.today() else "upcoming"
                BorrowerInstallment.objects.filter(pk=row.pk).update(
                    principal_paid=paid_values["principal"], interest_paid=paid_values["interest"], fee_paid=paid_values["fee"],
                    leader_commission_paid=paid_values["leader_commission"], penalty_paid=paid_values["penalty"],
                    paid_amount=paid_amount, status=status,
                )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_multiple_funding_proposals'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanborrower',
            name='collection_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collected_loan_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanborrower',
            name='collection_agent_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanborrower',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanborrower',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='removed_loan_borrowers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanborrower',
            name='replacement_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_requests', to='core.loanborrower'),
        ),
        migrations.AddField(
            model_name='repayment',
            name='loan_borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='core.loanborrower'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='source',
            field=models.CharField(choices=[('lender', 'Fonds preteur'), ('leader_commission', 'Commission chef de club')], default='lender', max_length=24),
        ),
        migrations.AlterField(
            model_name='loanborrower',
            name='status',
            field=models.CharField(choices=[('accepted', 'Acceptee'), ('pending', 'En attente'), ('declined', 'Refusee'), ('removed', 'Retiree')], default='pending', max_length=16),
        ),
        migrations.CreateModel(
            name='BorrowerInstallment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField()),
                ('principal_due', models.DecimalField(decimal_places=2, max_digits=16)),
                ('interest_due', models.DecimalField(decimal_places=2, max_digits=16)),
                ('fee_due', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('leader_commission_due', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('penalty_due', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('principal_paid', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('interest_paid', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('fee_paid', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('leader_commission_paid', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('penalty_paid', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('status', models.CharField(choices=[('upcoming', 'A venir'), ('due', 'Due'), ('partial', 'Partielle'), ('paid', 'Payee'), ('late', 'En retard'), ('transferred', 'Transferee')], default='upcoming', max_length=16)),
                ('loan_borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='core.loanborrower')),
            ],
            options={
                'ordering': ['due_date', 'number'],
                'constraints': [models.UniqueConstraint(fields=('loan_borrower', 'number'), name='unique_borrower_installment')],
            },
        ),
        migrations.RunPython(backfill_collective_debts, noop_reverse),
    ]
