# Generated by Django 5.2.16 on 2026-08-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_loanborrower_collection_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='destination',
            field=models.CharField(choices=[('cash', 'Recuperation externe'), ('lender_wallet', 'Compte preteur')], default='cash', max_length=24),
        ),
    ]
